version: '3.8'

services:
  app:
    image: bienes_raices
    container_name: bienes_raices
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mysqldb
    ports:
      - '8000:4000'
    networks:
      - app-network
  
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bienes_raices"
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge